In [1]:
import pandas as pd

First combine all the stats together

In [29]:
offense = pd.read_csv('offense_results.csv')
defense = pd.read_csv('defense_results.csv')
special = pd.read_csv('special_results.csv')

In [81]:
def clean_stats_df(df):
    print(len(df))
    df_new = df.drop(['Unnamed: 0', 'ranker','g'], axis=1).set_index(['school_name','year'])
    return df_new

In [82]:
clean_off = clean_stats_df(offense)
clean_def = clean_stats_df(defense)
clean_spec = clean_stats_df(special)

2318
2318
2318

In [76]:
all_stats = pd.merge(clean_off, clean_def, how='left', left_index=True, right_index=True)
all_stats = pd.merge(all_stats, clean_spec, how='left', left_index=True, right_index=True)

In [77]:
all_stats.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2318 entries, (Boise State, 2000) to (Rutgers, 2018)
Data columns (total 62 columns):
first_down                2318 non-null float64
first_down_pass           2318 non-null float64
first_down_penalty        2318 non-null float64
first_down_rush           2318 non-null float64
fumbles_lost              2318 non-null float64
pass_att                  2318 non-null float64
pass_cmp                  2318 non-null float64
pass_cmp_pct              2318 non-null float64
pass_int                  2318 non-null float64
pass_td                   2318 non-null float64
pass_yds                  2318 non-null float64
penalty                   2318 non-null float64
penalty_yds               2318 non-null float64
points                    2318 non-null float64
rush_att                  2318 non-null float64
rush_td                   2318 non-null float64
rush_yds                  2318 non-null float64
rush_yds_per_att          2318 non-null float64
tot_plays                 2318 non-null float64
tot_yds                   2318 non-null float64
tot_yds_per_play          2318 non-null float64
turnovers                 2318 non-null float64
opp_first_down            2318 non-null float64
opp_first_down_pass       2318 non-null float64
opp_first_down_penalty    2318 non-null float64
opp_first_down_rush       2318 non-null float64
opp_fumbles_lost          2318 non-null float64
opp_pass_att              2318 non-null float64
opp_pass_cmp              2318 non-null float64
opp_pass_cmp_pct          2318 non-null float64
opp_pass_int              2318 non-null float64
opp_pass_td               2318 non-null float64
opp_pass_yds              2318 non-null float64
opp_penalty               2318 non-null float64
opp_penalty_yds           2318 non-null float64
opp_points                2318 non-null float64
opp_rush_att              2318 non-null float64
opp_rush_td               2318 non-null float64
opp_rush_yds              2318 non-null float64
opp_rush_yds_per_att      2318 non-null float64
opp_tot_plays             2318 non-null float64
opp_tot_yds               2318 non-null float64
opp_tot_yds_per_play      2318 non-null float64
opp_turnovers             2318 non-null float64
fg_pct                    2065 non-null float64
fga                       2065 non-null float64
fgm                       2318 non-null float64
kick_points               2318 non-null float64
kick_ret                  2318 non-null float64
kick_ret_td               2318 non-null float64
kick_ret_yds              2318 non-null float64
kick_ret_yds_per_ret      2318 non-null float64
punt                      2318 non-null float64
punt_ret                  2318 non-null float64
punt_ret_td               2318 non-null float64
punt_ret_yds              2318 non-null float64
punt_ret_yds_per_ret      2318 non-null float64
punt_yds                  2318 non-null float64
punt_yds_per_punt         2318 non-null float64
xp_pct                    2318 non-null float64
xpa                       2318 non-null float64
xpm                       2318 non-null float64
dtypes: float64(62)
memory usage: 1.2+ MB

Now bring in the conference standings and final ranks.

In [79]:
standings = pd.read_csv('standings_results.csv')

In [83]:
def clean_standings_df(df):
    print(len(df))
    df_new = df.drop(['ranker'], axis=1).set_index(['school_name','year'])
    return df_new

In [84]:
clean_stand = clean_standings_df(standings)

2318

In [86]:
all_stats = pd.merge(all_stats, clean_stand, how='left', left_index=True, right_index=True)

In [87]:
all_stats

,,first_down,first_down_pass,first_down_penalty,first_down_rush,fumbles_lost,pass_att,pass_cmp,pass_cmp_pct,pass_int,pass_td,...,points_per_g,rank_final,rank_min,rank_pre,sos,srs,win_loss_pct,win_loss_pct_conf,wins,wins_conf
school_name,year,,,,,,,,,,,,,,,,,,,,,
Boise State,2000,23.9,13.5,1.5,8.9,0.6,33.8,20.5,60.5,0.7,3.4,...,44.3,NaN,NaN,NaN,-8.80,6.78,0.833,1.000,10.0,5.0
Miami (FL),2000,21.2,12.1,1.4,7.7,1.5,30.9,18.0,58.2,0.5,2.4,...,42.2,2.0,2.0,5.0,5.22,23.22,0.917,1.000,11.0,7.0
Florida State,2000,25.3,14.5,2.8,8.0,0.7,39.1,24.2,61.8,1.2,3.0,...,39.3,5.0,1.0,2.0,5.59,23.13,0.846,1.000,11.0,8.0
Nebraska,2000,22.9,5.2,0.9,16.8,0.8,15.6,7.6,48.8,0.7,1.0,...,43.5,8.0,1.0,1.0,4.51,19.01,0.833,0.750,10.0,6.0
Virginia Tech,2000,22.5,6.5,1.2,14.7,1.5,20.5,10.5,51.3,0.6,0.8,...,40.3,6.0,2.0,11.0,4.00,19.42,0.917,0.857,11.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Michigan State,2018,20.2,11.2,1.9,7.1,0.6,38.2,19.6,51.4,1.1,0.9,...,18.7,NaN,11.0,11.0,5.08,6.01,0.538,0.556,7.0,5.0
UTEP,2018,15.5,7.5,1.4,6.6,0.8,27.0,13.4,49.7,1.6,0.8,...,17.7,NaN,NaN,NaN,-8.46,-22.88,0.083,0.125,1.0,1.0
Central Michigan,2018,15.1,6.4,1.7,7.0,0.8,30.2,14.7,48.6,1.5,0.8,...,15.0,NaN,NaN,NaN,-4.18,-15.76,0.083,0.000,1.0,0.0
UTSA,2018,15.3,8.1,1.3,5.8,0.7,33.7,17.0,50.5,0.8,0.8,...,14.2,NaN,NaN,NaN,-4.40,-16.40,0.250,0.250,3.0,2.0
Rutgers,2018,15.2,6.0,2.0,7.2,0.6,29.2,14.3,48.9,1.8,0.4,...,13.5,NaN,NaN,NaN,4.10,-9.65,0.083,0.000,1.0,0.0